---

  - name: Install the OpenAS repository
    yum:
      name: https://as-repository.openvpn.net/as-repo-centos7.rpm
      state: latest

  - name: Install the OpenAS rpm 
    yum:
      name: openvpn-as
      state: present

  - name: Ensure VPN is accessible
    firewalld:
      port: 943/tcp
      permanent: yes
      state: enabled

  - name: Ensure VPN is accessible
    firewalld:
      port: 943/udp
      permanent: yes
      state: enabled
      